[plugin]
repository = "https://github.com/SamuelSapp/FastWaymarksPlugin.git"
commit = "d6aad095fc511fff693e996c98c03c3ce27d9cce"
owners = ["SamuelSapp"]
project_path = "FastWaymarksPlugin"
changelog = "Initial Submission"
